version: "3.6"
services:
  app:
    container_name: peps
    build: 
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      # Ports exposed outside, they should match config
      - 8501:8501
